[package]
name = "rust-for-nodejs-developers"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }

[dependencies.sqlx]
version = "0.8.3"
features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "macros",
  "migrate",
  "uuid",
  "time",
  "json",
]
